### PR TITLE
Allow imports into other python scripts

### PR DESCRIPTION
**Pull request by KPLauritzen**
Now you can do
`from rmsd import calculate_rmsd` in another python script

### CODE REVIEW

**Comment by Ashafix** [comment]
perhaps we can merge this with https://github.com/charnley/rmsd/pull/16?

**Comment by charnley** [comment]
Maybe it would be better to just rename calculate_rmsd to calculate_rmsd.py than to have symbolic links? @KPLauritzen

**Comment by KPLauritzen** [comment]
Yes @charnley, that seems better. I would guess that is also more in line with standard practice

**Comment by charnley** [comment]
Agreed. It will probably break some peoples symbolic links (including mine) but that is a sacrifice I'm willing to make for easier import and transparency.

**Pull request merged**
