### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by charnley**
reorder branch merge

### CODE REVIEW

**Comment by benjfitz** [comment]
Something does not seem correct with the output. Using SF2HClBrI-a and -xz as examples, these are identical except the second has X coordinates swapped with Z coordinates. Hence, the Quater RMSD should be 0.0, but I am getting 1.4000679305.

**Comment by benjfitz** [comment]
I think I know what is going on with the re-ordered RMSD values being larger than they should. The Hungarian and brute methods perform 3 transformations to find the optimal re-ordering: atom re-ordering, coordinate swaps (eg X and Z swapped), and reflections. reorder_brute and reorder_hungarian only return the first of these transformations, but not the second two transformations. Hence, when main calls the re-ordering functions the subsequent RMSD calculations at the very end of main do not use q coordinates having the proper swaps and reflections.

**Comment by benjfitz** [comment]
One further thought, was your idea for debug and debug_abridged to read an environment variable from the command line, or did you have another idea for accessing the debugging?

**Comment by benjfitz** [comment]
Hey Jimmy,
Did either of my sets of comments/issues go through? In both cases I could
not find them the next day.

In short, there is a problem with the info passed back to main from
hungarian and brute which keeps the final Kabsch and Quaternion RMSD values
from being correct.
Thanks,
Benj

**Comment by charnley** [comment]
Hej Benj, 

Yep, I read the above comments :) I think I understand what I did wrong, just didn't have time to look at it yet. I have an idea to fix it, still keeping the view structure.

Btw, in general if you find problems you should add them to https://github.com/charnley/rmsd/issues. Then it is also easier to track and other people to comment on.

**Comment by benjfitz** [comment]
Hey Jimmy,
For sure. It was only after I added the comments to the dev branch it
dawned on me I should have used the issues feature instead. When the dev
branch went away I created two issues, but those also evaporated so I must
have done something incorrectly.

Agreed, these should be easy fixes. :-)
Thanks,
Benj

**Pull request merged**
