### PR TITLE
attempt exporting both *.xyz and (reflection based) RMSD

### PR DESCRIPTION
**Pull request by nbehrnd**
Scrutinizing multiple `*.xyz` files in a round-Robin tournament, each representing
a cluster of about a dozen identical constitutionally identical molecules, I sought
accessing both the newly aligned orientation of modelB as well as the corresponding
RMSD describing the goodness of fit for one and the same test performed.  Test data,
adapted moderator script, generated new alignment `*.xyz` and report obtained via

`python3 multipro.py > 20190328-RMSDandXYZ-test.txt`

on an instance of Linux Xubuntu 18.04.2 LTS (64 bit) with Python 3.6.7 are enclosed
in the attached zip.archive.

- As  expected, the `*.xzy` files written still are readable for either Jmol (14.6.2_2016.11.05),
or Avogadro (1.2.0).  Avogadro does not connect all atoms per molecule in the cluster
`*.xyz` data because originally the atom types intentionally were "unified" to one form --
here oxygen -- to permit any comparison by `calculate_rmsd.py`.

- There might be a better way to toggle between an output of "just RMSD" or "just the new
coordinates", on one hand, or "RMSD and new coordinates" as a new, third option.  So far,
my attempts to alter the parser-section (lines #811 and following) however failed to
accomplish this because I lack working experience with the corresponding module.  This is
why the original export instructions (`done and done`, lines #1021 following) are only
commented out.

- In difference to the earlier version of `calculate_rmsd.py`, a round-Robin tournament
testing of multiple `.xyz` no longer will systematically overwrite the newly written coordinate
file if the second structure file to test with happens to be the same.  As seen with kdiff3
(0.9.98) the coordinates in the piped CLI output nicely reappear in the separately written
`*.xyz` about the new alignemnt.  Due to the distributed computation on multiple CPU,
however, the order data input / launch of individual tests need not correspond to the
consecution of data output (reflection-based RMSD) on the CLI.  This is why the output
of "which files were tested" and their RMSD was reorganized.

- While the RMSD exported with `--use-reflections` in a manual test of a modelA and a
modelB appear again in the present batchwise test engaging `--use-reflections -p` with
the last print instruction of
`print("{0}.format(result_rmsd))`
(old line #1036), it seems to me that the other rmsd (`result_rmsd = rmsd(p_coord, q_coord)`,
on #1031 and `result_rmsd = rotation_method(p_coord, q_coord)` on oud #1034 differ
from the former.   It were helpful if you might confirm that my current selection of RMSD,
as the one for either method `--use-reflection` / inversion testing, or stereo conservative
method `--use-reflection-retain-stereo` matches my intention.  Could it be useful to "unify"
the RMSD such that eventually -- regardless if the alignment proceeds only by translation
and rotation, or considers even or potentially odd-numbered reflection -- were expressed
by one variable only?

[20190328-nbehrnd-documentation.zip](https://github.com/charnley/rmsd/files/3017803/20190328-nbehrnd-documentation.zip)

### CODE REVIEW

**Comment by larsbratholm** [comment]
I don't understand what this pull request is meant to do. It changes the output slightly, but for what reason? Can you explain the reasoning and benefit in 50 words or less?

**Comment by nbehrnd** [comment]
The pull request focus' is calculate_rmsd.py.  In my series with
     50...150 model data, the more interesting tests take at least 10s
     each. Instead of determining either RMSD .OR. geometry (now, two
     determinations), a simultaneous output of RMSD and separate *.xyz
     file written by one test (suggested) safes me one run.

     PS: Correct, multipro.py attempts to gain some speed independently
     of calculate_rmsd.py -- and does not count here.

**Comment by nbehrnd** [comment]
The pull request focus' is calculate_rmsd.py.  In my series with
     50...150 model data, the more interesting tests take at least 10s
     each. Instead of determining either RMSD .OR. geometry (now, two
     determinations), a simultaneous output of RMSD and separate *.xyz
     file written by one test (suggested) safes me one run.

     PS: Correct, multipro.py attempts to gain some speed independently
     of calculate_rmsd.py -- and does not count here.
[documentation.zip](https://github.com/charnley/rmsd/files/3020375/documentation.zip)

**Comment by charnley** [comment]
The feature you are asking for would be better solved by using rmsd as python package.

**Pull request closed without merging**
