### PR TITLE
Enhancement of Kabsch-based routines to work with weighted data

### PR DESCRIPTION
**Pull request by CharlieLaughton**
Hi,

Thanks for a useful little package. If you are interested, I have tweaked the Kabsch-related least-squares fitting routines to accept an optional weights argument, so that, for example, the routines can be used for mass-weighted fitting. I've also added a utility function "Kabsch_fit()", so:

nP = kabsch_fit(P, Q. W)

results in nP being a copy of P least-squares fitted to Q, weighted according to W.

I added a couple of relevant tests as well.

### CODE REVIEW

**Comment by nbehrnd** [comment]
An interesting thought indeed; crystallographically speaking it may be used to
emphasize more on heavier atoms easier to localize in diffraction experiments
than lighter ones.  Such is already implemented in [aRMSD](https://github.com/armsd/aRMSD)
(forked [here](https://github.com/armsd/aRMSD) with optional choice between mass,
proton count, scatter factor and it will be interesting to compare with your addition.
(Contrasting to calculate_rmsd.py, aRMSD prefers the pairwise comparison, though.)

A question / feature suggest: since your feature already allows one form of gradual
attenuation of contribution, what about a function scaling the contribution by distance,
by power-of-two, or even by power-of-three such that differences spot farther away
do not account as much that those in proximity to the centre of the centroid?  Perhaps
acting independently of the option "scaling by mass", but why not scale by mass .AND.
distance?  Just as a thought.

**Comment by CharlieLaughton** [comment]
Ah - perhaps I should clarify - although I suggested that the weights argument W might be a vector of atomic masses, to do mass-weighted fitting, there is no requirement that it is. A user can set W to whatever they like - e.g. to implement your suggestions.

**Comment by charnley** [comment]
Hi @CharlieLaughton. Sorry for the long delay of attention on this pull request! It looks great, I only have two points.

- Keep all weights as keyword (ei. W=None), also when calling functions, e.i.

    U = kabsch(P, Q, W) # not keyword
    U = kabsch(P, Q, W=W) # keyword

- Make a separate `def kabsch` function called `kabsch_weighted`. I know that some functionality will be copied over, but I feel kabsch with weights is a different problem to solve and therefore requires a different function. Something like this

   if W is None:
       U = kabsch(P, Q)
    else:
        U = kabsch_weighted(P, Q, W)

If you agree and correct those small changes I will merge your pull request as soon as possible

best regards Jimmy

**Comment by CharlieLaughton** [comment]
Hi Jimmy,

My turn to apologies for the delay – will do!

Best wishes,

Charlie

**Comment by CharlieLaughton** [comment]
Hi Jimmy, OK, this should be ready to go. Looking again at my code I discovered a bug, and to fix this and address your points I've ended up re-writing quite a bit. 

So that the weighted fitting code treads more lightly on your existing code, I have created three weighting-specific functions: kabsch_weighted(), kabsch_weighted_fit(), and kabsch_weighted_rmsd(). The only entry point from your code into these new functions is in kabsch_rmsd(), the other is via my new kabsch_fit()

**Pull request merged**
